data = '''I am a very passionate and emotional person. I’m not saying that I cry all the time but if I don’t feel an emotion when I’m working, doing homework or reading then something is not clicking. This applies to learning and education. I have always been very grateful to learn in a school. Of course we all learn outside of school from our parents, observations and society. But learning in a school is a luxury and going to college is a luxury. The fact that I can go back to school into a teaching program and my biggest worry is to keep my grades up is amazing. I have never felt that learning was about someone just giving me information because that’s not what it is. Becoming educated is an empowering and transformative experience. During K-12 schooling I had some teachers who really went out of their way to teach us something new. Luckily, these few teachers did the trick. I read about different perspectives and I was challenged a lot. College rocked my world because I began to see myself in the curriculum. I began to see how I could influence people and situations around me. I grew so much in college but I did not like that I had to wait to college to really reach my full potential. I wanted to become a teacher to share my passion for learning and also make students aware that they can be actors in the world around them. I feel teachers are there to help us understand the world around us. In an English class I feel this is done by reading about ourselves in the curriculum.
Teaching was very natural for me. I felt comfortable and confident working in all my classrooms. I was fortunate to have the support from all supervising teachers and they provided me guidance and knowledge as I continued to grow in the classroom. I couldn’t wait to go to college so I could focus on teaching every day and officially start my journey as a future
Education is something that I have always valued. My passion of learning has only intensified since I was younger. The constant challenge that comes with learning new things is how I know that I am bettering myself. I have always been a very self-dependant person, and education wizens me and allows me to make my own decisions.
Education is something that I have always valued. My passion for learning has only intensified since I was a child. I crave the constant challenge that comes with learning because it’s how I know that I am bettering myself. I have always been a very self-dependant person, and education
Becoming a high school teacher had always been the goal. As a young child and growing up with a multitude of siblings, children were my life. The aspiration stemmed from a desire to teach the next generation, to be a leader for the mind and guide them onto the next phase of their lives. I saw my favorite teachers do it with the kind of patience and discipline that only a teacher could have and after job shadowing Scott Hatfield, the social studies and current events teacher at Summit Academy North Muddle School, I realized that I am not fit for that lifestyle like I thought.
I am currently a Kindergarten teacher at Our Lady of Trust Academy. Although it is a wonderful private institution, my goal is to teach at a public school. I have chosen this career path because I am passionate about working with children, while they are developing their foundational skills. I believe that by receiving a high quality education; that goes beyond remembering and understanding, students can master the core material through analyzing and creating. This will give learners a strong base to build upon, setting students on the path to be successful in high school, and go on to be career and
Upon first entering college, I struggled deciding at such a young age what I wanted to do for the rest of my life. Through babysitting and volunteering with pre-school aged children at my church and through a school program called STARS, it became evident to me I had a love for helping children. It fascinated me to see how they viewed the world around them and how quickly they learned new truths everyday. Nevertheless, I knew I would not get the full enjoyment interacting with children as a schoolteacher because the teacher to student ratio is so large. Classroom demands would make it much more difficult to devot individualized attention to each student, and I did not like that concept. So
Becoming a middle school teacher changed how I felt about what kind of teacher I want to be. When I graduated from college in 2009, I was sure that I wanted to be a 4th or 5th grade teacher. I had student taught in 5th grade, and I really enjoyed it. I immediately began applying for elementary teaching positions. Thankfully, a position opened up in the district I lived in, student taught in, and where my children attended school. I was so excited because a position was open in 5th grade! I could work with the teacher I student taught with, in the grade I student taught in.
I always thought I would be a teacher and I would make differences in lives and it would be the greatest experience in the world for me, yet being a teacher wasn’t enough, I had a need to expand my education. I decided that perhaps I needed a new career, however, I felt certain education remained my passion. I began to explore new areas of education and I realized I still want to be a member of a classroom, a school and curriculum. I aspire to guide those leading our classrooms.
I have had a lifetime goal to attend college, it just didn’t happen early in life. When I first came to CCU, there was no doubt that getting my bachelors in early childhood would be my major. My passion has always been young children. It started when I babysat as a young teenager and has continued in my life as a preschool teacher. Education is constantly changing: therefore, I feel I need to have more knowledge and wisdom to be the best teacher possible. Education is by far one of the most important tools to have a successful life. With diligence, I want to be a leading educator and to be a gateway for my students to learn. It’s exhilarating how many lives a teacher will touch each day. A teacher has the power to reach out and make learning a positive and memorable experience for every child. Furthermore, teachers are one of the first caregivers for young children. Although I am not at the beginning of my career, while at CCU, I will grow in faith, help and learn from others, and strive to graduate with honors.
Some teachers say that they have had the dream of being a teacher their entire life. I on the other hand would not strive for this dream until my second semester of college at the College of Southern Nevada, and I often ponder how different my life would have been if I would have had a teaching end goal from the beginning.
when i was growing up i never thought i would want to become a teacher. I always thought i would be something more exciting like a storm chaser, or a astronaut. a teacher back then to me was nothing special, it was just a boring job dealing with ungrateful children. Then when i entered high school I realized teaching students wasn’t as bad as i thought. I started tutoring kids in both math and history. i loved it when they would begin to understand a problem they were stuck on or they remembered that one date in history so they can pass a test. It was amazing.
For me, the decision to become a teacher is more of a way of life than a career. I have always loved school, practicing at being school marm from a young age, and voraciously devouring every shred of education offered me in my career as a student. If it were possible, I would be a student for the rest of my life. And then I still would not have learned enough. As a teacher, I hope to instill this appetite for knowledge in secondary students. They are, after all, the future leaders of the world, and what better place to expand the minds of the generations to come than here in Appalachia where education programs, especially the sciences, which I plan to teach, are poorly funded and children’s dreams
Education is a key element that directs one's life to success. By having knowledge one holds the power to make goals a reality. Teachers are responsible to help goals, such as, learning to read become a reality. It is the responsibility of the teacher to give the students the best quality of education in order for the students to be able to have a positive experience as well success in life. I feel students should be given the opportunity to learn the facts, the truth, not just parts of it. I feel as an educator one needs to give the students the opportunity to
I personally believe that education is one of the most important things to achieve in life. No matter what it can never be taken away from you. From my observations and experiences in the classroom each child is unique in his or her own way. Students inside a classroom needs a teacher who will make them feel secure, comfortable and in a stimulating atmosphere. These aspects help to attain growth, mature emotionally, intellectually, physically, and socially. It is my desire as an educator to meet the needs of my students in any way possible, so that they are able to meet their fullest potential in life. Children are the future, so as a teacher I need to take all the necessary steps to get them to their fullest potential. I believe that the teacher should act as a guide, allowing the child's natural curiosity to direct his or her learning, and promoting respect for all people are conductive to establishing productive students of tomorrow.
I want to become a teacher because I believe that all students are unique in their own way. I want to teach because I want to know that I am making a positive difference in the lives of students. Also, because teaching will allow me to connect with students in ways I've never been able to. I've always felt joy when I am around kids, it brings a sense of excitement. To me it is not simply a job but instead a purpose and my mission. I believe teachers should not be alone in educating their students. Parents, families and communities need to work together to support and enrich the lives of their children. By being a part of your child's education, you are showing them that you care and support them.
'''

# Goal:
# 1. Count how many times specific emotional words (e.g., "love", "hurt", "fear") appear.
# For list:
love_appear = data.count("love")
words = [word.lower() for word in data.split()]
def count_word(word):
    count = 0
    for i in words:
        if i == word:
            count += 1
    return count
count_word("love")

# For string:
def count_word(word):
    count = data.count(word)
    i = data.find(word)
    j = i + len(word) - 1
    return count


print(count_word("love"))

# 2. Calculate what percentage of the total words are emotional.
